import {Message} from "./Message";

export enum SocketChannel {

    // Channels to Notify Clients through WebSockets
    ClientManagedNotification = Message.AppNamePrefix + '.client.manage.notify',
    DeviceManagedNotification = Message.AppNamePrefix + '.device.manage.notify',
    LightManagedNotification = Message.AppNamePrefix + '.light.manage.notify',
    LightGroupManagedNotification = Message.AppNamePrefix + '.lightGroup.manage.notify',
    BridgeManagedNotification = Message.AppNamePrefix + '.bridge.manage.notify',
    AlarmManagedNotification = Message.AppNamePrefix + '.alarm.manage.notify',
    FileManagedNotification = Message.AppNamePrefix + '.file.manage.notify',
    SceneManagedNotification = Message.AppNamePrefix + '.scene.manage.notify',
    LogbookManualInputManagedNotification = Message.AppNamePrefix + '.logbook_manual_input.manage.notify',
    LogbookManualEntryManagedNotification = Message.AppNamePrefix + '.logbook_manual_entry.manage.notify',
    SettingsManagedNotification = Message.AppNamePrefix + '.settings.manage.notify',
    SignalKDataManagedNotification = Message.AppNamePrefix + '.signalK_data.manage.notify',
    TrackDetailManagedNotification = Message.AppNamePrefix + '.track_detail.manage.notify',
    TrackManagedNotification = Message.AppNamePrefix + '.track.manage.notify',
    VdrSettingsManagedNotification = Message.AppNamePrefix + '.vdr_settings.manage.notify',
    VoiceEntryManagedNotification = Message.AppNamePrefix + '.voice_entry.manage.notify',
    LogbookEntryReminderNotification = Message.AppNamePrefix + '.logbook_entry.notify',
    NightModeStateManagedNotification = Message.AppNamePrefix + '.night_mode.state.notify',
    TestAlarmNotification = Message.AppNamePrefix + '.alarm.test.notify',

    // Channels to Transfer Object through WebSockets
    ClientManagedObject = Message.AppNamePrefix + '.client.manage.object',
    DeviceManagedObject = Message.AppNamePrefix + '.device.manage.object',
    LightManagedObject = Message.AppNamePrefix + '.light.manage.object',
    LightGroupManagedObject = Message.AppNamePrefix + '.lightGroup.manage.object',
    BridgeManagedObject = Message.AppNamePrefix + '.bridge.manage.object',
    AlarmManagedObject = Message.AppNamePrefix + '.alarm.manage.object',
    FileManagedObject = Message.AppNamePrefix + '.file.manage.object',
    SceneManagedObject = Message.AppNamePrefix + '.scene.manage.object',
    LogbookManualInputManagedObject = Message.AppNamePrefix + '.logbook_manual_input.manage.object',
    LogbookManualEntryManagedObject = Message.AppNamePrefix + '.logbook_manual_entry.manage.object',
    SettingsManagedObject = Message.AppNamePrefix + '.settings.manage.object',
    SignalKDataManagedNObject = Message.AppNamePrefix + '.signalK_data.manage.object',
    TrackDetailManagedObject = Message.AppNamePrefix + '.track_detail.manage.object',
    TrackManagedObject = Message.AppNamePrefix + '.track.manage.object',
    VdrSettingsManagedObject = Message.AppNamePrefix + '.vdr_settings.manage.object',
    VoiceEntryManagedObject = Message.AppNamePrefix + '.voice_entry.manage.object',
    AudioRecordStateObject = Message.AppNamePrefix + '.audio_record.state.object',
    WhisperServiceStateObject = Message.AppNamePrefix + '.whisper_service.state.object',
    WhisperServiceResultObject = Message.AppNamePrefix + '.whisper_service.result.object',
    VdrServiceStateObject = Message.AppNamePrefix + '.vdr_service.state.object',
    SystemUpdateLogObject = Message.AppNamePrefix + '.system_update.object',
    AlarmTriggeredObject = Message.AppNamePrefix + '.alarm.triggered.object',
    NightModeStateManagedObject = Message.AppNamePrefix + '.night_mode.state.object',
    WeatherApiCurrentForecastResult = Message.AppNamePrefix + '.weather_api.current_forecast.result.object',
    WeatherApiDailyForecastResult = Message.AppNamePrefix + '.weather_api.daily_forecast.result.object',
    EngineLogUpdateObject = Message.AppNamePrefix + '.engine_log_update.object',
    EngineLogUpdateObjectByDay = Message.AppNamePrefix + '.engine_log_update.object.byDay',
    PowerConnectionObject = Message.AppNamePrefix + '.power_connection.object',
    SignalKDataBroadcastObject = Message.AppNamePrefix + '.signalK_data.broadcast.object',
}
