import {Component, OnInit} from '@angular/core';
import {Router} from '@angular/router';
import {CoreService} from '../../../../service/core.service';
import {AlertsService, AlertState} from "../../../../service/alerts.service";
import {Resource} from "../../../../Resource";
import {LoaderService} from "../../../../service/loader.service";
import {CloudAuthService} from "../../../../client-sdk/services/cloud-auth.service";
import {UserDetails} from "../../../../client-sdk/cloud/models/UserDetail";
import {Gateway} from "../../../../client-sdk/cloud/models/Gateway";
import {Session} from "../../../../client-sdk/cloud/models/Session";
import {CloudUserDetailsService} from "../../../../client-sdk/services/cloud-user-details.service";
import {CloudGatewayService} from "../../../../client-sdk/services/cloud-gateway.service";
import {ConfigurationService} from "../../../../service/configuration.service";
import {HttpService} from "../../../../client-sdk/services/http.service";
import {AuthService} from "../../../../client-sdk/services/auth.service";

@Component({
  selector: 'app-cloud-account',
  templateUrl: './cloud-account.component.html',
  styleUrls: ['./cloud-account.component.scss']
})
export class CloudAccountComponent implements OnInit {

  private readonly cloudAuthRoute = '/cloud/auth';

  session: Session;
  user: UserDetails;

  connected = false;

  get displayName() {
    if (this.user == null) {
      return '';
    }
    if (this.user.firstname !== '') {
      return `${this.user.firstname}`;
    }
    return this.user.user.email;
  }

  get gateways() {
    if (this.user == null) {
      return [];
    }
    const gateways: Gateway[] = [];
    gateways.push(...this.user.gateways);
    gateways.push(...this.user.permitted_gateways);
    return gateways;
  }

  constructor(private cloudAuthService: CloudAuthService,
              private cloudUserDetailsService: CloudUserDetailsService,
              private cloudGatewayService: CloudGatewayService,
              private gatewayConfigurationService: ConfigurationService,
              private httpService: HttpService,
              private gatewayAuthService: AuthService,
              private router: Router,
              private coreService: CoreService,
              private alert: AlertsService,
              private loader: LoaderService) {
    //
  }

  async ngOnInit(): Promise<void> {
    this.loader.startLoading();

    this.connected = await this.coreService.isConnectedAndAuthorized();

    try {
      this.session = await this.cloudAuthService.checkSession();
    } catch (e) {
      this.loader.stopLoading();
      await this.router.navigate([this.cloudAuthRoute]);
      return;
    }

    try {
      this.user = await this.cloudUserDetailsService.getUserDetails();
    } finally {
      this.loader.stopLoading();
    }
  }

  getGatewayName(gateway: Gateway): string {
    if (gateway.name !== '' && gateway.name != null) {
      return gateway.name;
    }
    return `Unbenannt: ${gateway.id}`;
  }

  async connect(gw: Gateway): Promise<void> {
    this.loader.startLoading();

    try {
      const gateway = await this.cloudGatewayService.getGateway(gw.id);
      const tokenResult = await this.cloudGatewayService.addClient('Generated by Cloud', gateway.id, true);

      for (const ipObj of gateway.ips) {

        if (ipObj.ip == null) {
          continue;
        }

        if (await this.gatewayConfigurationService.tryConnect(ipObj.ip)) {

          localStorage.setItem('MyShip.ServerUrl', ipObj.ip);
          this.httpService.setApi();

          if (await this.gatewayAuthService.checkAuth() === false) {
            if (await this.gatewayAuthService.auth(tokenResult.token.toString())) {
              window.location.href = '/';
              // await this.router.navigate(['/home']);
              return;
            }
          } else {
            this.loader.stopLoading();
          }

          break;
        }
      }

    } finally {
      this.loader.stopLoading();
    }

  }

  async logout(): Promise<void> {
    this.loader.startLoading();
    if (await this.cloudAuthService.logout()) {
      await this.router.navigate([this.cloudAuthRoute]);
    } else {
      this.alert.alert(AlertState.Error, Resource.CloudLogoutFailed);
    }
    this.loader.stopLoading();
  }

}
