export enum SignalKIdentifier {
    electricalAlternators0RevolutionsValue = 'electrical.alternators.0.revolutions',
    electricalBatteriesMainLifetimeDischargeValue = 'electrical.batteries.main.lifetimeDischarge',
    electricalBatteriesMainVoltageValue = 'electrical.batteries.main.voltage',
    electricalBatteriesMainCurrentValue = 'electrical.batteries.main.current',
    electricalBatteriesMainCapacityConsumedChargeValue = 'electrical.batteries.main.capacity.consumedCharge',
    electricalBatteriesMainCapacityStateOfChargeValue = 'electrical.batteries.main.capacity.stateOfCharge',
    electricalBatteriesMainCapacityTimeRemainingValue = 'electrical.batteries.main.capacity.timeRemaining',
    navigationPositionValueLongitude = 'navigation.position.longitude',
    navigationPositionValueLatitude = 'navigation.position.latitude',
    navigationGnssSatellitesValue = 'navigation.gnss.satellites',
    navigationGnssAntennaAltitudeValue = 'navigation.gnss.antennaAltitude',
    navigationGnssHorizontalDilutionValue = 'navigation.gnss.horizontalDilution',
    navigationGnssDifferentialAgeValue = 'navigation.gnss.differentialAge',
    navigationGnssDifferentialReferenceValue = 'navigation.gnss.differentialReference',
    navigationSpeedOverGround = 'navigation.speedOverGround',
    navigationCourseOverGroundTrue = 'navigation.courseOverGroundTrue',
    navigationCourseOverGroundMagnetic = 'navigation.courseOverGroundMagnetic',
    environmentOutsideTemperature = 'environment.outside.temperature',
    environmentWindAngleApparent = 'environment.wind.angleApparent',
    environmentWindSpeedApparent = 'environment.wind.speedApparent',
    navigationSatellitesInView = 'navigation.gnss.satellitesInView',
    navigationSatellitesInViewSatellites = 'navigation.gnss.satellitesInView.satellites'
}