import {AppDataSource} from "../DatabaseProvider";
import UserService from "../services/userService";
import {String} from "../services/helpers/String";
import * as process from "process";

const prefix = '[MyShip - CLI] Script: generateClientTokenScript -';

const execute = async () => {

    await AppDataSource.initialize();

    const token = String.generateNumber(6);
    let commentArg = process.argv[2];
    const adminFlag = process.argv[3] === '1';

    if (commentArg == null || commentArg === "") {
        commentArg = 'No comment, Token generated by CLI';
    }

    await UserService.create(token, commentArg, adminFlag);

    console.log(`${prefix} Generated Token: ${token} ${adminFlag ? ' - Admin-Flag' : ''} - Comment: ${commentArg}`);

};

execute().then(() => {
    console.log(`${prefix} Executed`);
    process.exit(0);
});